#!/usr/bin/env bash
#
# IEs 4 Linux
# Developed by: Sergio Luis Lopes Junior <slopes at gmail dot com>
# Project site: http://tatanka.com.br/ies4linux
#
# Released under the GNU GPL. See LICENSE for more information

# Discover ies4linux installation folder
IES4LINUX=`dirname "$0"`
cd "$IES4LINUX"
export IES4LINUX=`pwd`

source lib/functions.sh
initDebug
initVariables
initLanguage
checkDependencies

# Configure options
{
	# Get command-line options
	while [ $# -gt 0 ]; do
		case "$1" in
		--install-ie6 | --install-flash)   shift;;
		--install-ie55)     INSTALLIE55=1;   shift ;;
		--install-ie5)      INSTALLIE5=1;    shift ;;
		--install-ie2)      INSTALLIE2=1;    shift ;;
		--install-ie15)     INSTALLIE15=1;    shift ;;
		--install-ie1)      INSTALLIE1=1;    shift ;;
	
		--beta-install-ie7) INSTALLIE7=1;    shift ;;
	
		--no-flash) INSTALLFLASH=0;  shift ;;
		--no-icon)  CREATE_ICON=0;   shift ;;
		
		--basedir)          BASEDIR=$2;     shift 2 ;;
		--bindir)           BINDIR=$2;      shift 2 ;;
		--downloaddir)	    DOWNLOADDIR=$2; changeddownloaddir=1; shift 2 ;;
		
		--wget-flags)       WGETFLAGS=$2;   shift 2 ;;
		--no-color)	    NOCOLOR=1;	   shift 1 ;;
	
		--locale)
			CHOOSED_IE6_LOCALE=$(echo "$2" | tr a-z A-Z)
			shift 2
			;;
		--list-locales)
			echo $IE6_LOCALES | fmt -w 40
			exit 0
			;;
	
		--easter-eggs)
			cat <<__END_EGGS__
IEs4Linux can do other useful (?!) things:

--install-ie1         Install IE 1.0
--install-ie15        Install IE 1.5
--install-ie2         Install IE 2.0
__END_EGGS__
			exit 0
			;;
		--help | -h)
			cat <<__END_HELP__
	
Usage: ./ies4linux [OPTIONS]

This script downloads and automagically installs multiple versions of
Microsoft Internet Explorer on Wine.

Without any option, IEs4Linux will:
- install IE6
- install Adobe Flash 9
- create icons on Desktop

You can configure other things:

Installation options:

--install-ie55         Install IE5.5 in BASEDIR/ie55/
--install-ie5          Install IE5 in BASEDIR/ie5/
--no-flash             Don't install Adobe Flash Player 9
--no-icon              Don't create an icon in Desktop

Configurations:

--locale LOCALE        The locale for the installation [$GUESSED_IE6_LOCALE]
--wget-flags FLAGS     Extra flags for wget [$WGETFLAGS]
--list-locales         Display all possible locales and exit

Directories:

--basedir BASEDIR      Base location for installs [$BASEDIR]
--bindir BINDIR        Location of your bin folder [$BINDIR]
--downloaddir DLDIR    Where downloads will go [BASEDIR/$DOWNLOADDIR_SUFFIX]

Other options:

--no-color             Don't show colors
--help / -h            Display this message and exit OK

Beta options:

--beta--install-ie7    Install Internet Explorer 7 (BETA INSTALLER!)

__END_HELP__
			exit 0
			;;
	
		*)
			echo "Error: unknown option \"$1\""
			if echo "$1" | grep '=' >/dev/null; then
				echo "Options are not GNU-style"
				echo "  i.e. don't use: --option=value"
				echo "     use instead: --option value"
			fi
			echo "run \"./ies4linux --help\" for more info"
			exit 1
			;;
		esac
	done
	
	# Hack for downloaddir
	if [ "$changeddownloaddir" != "1" ]; then
		DOWNLOADDIR="$BASEDIR/$DOWNLOADDIR_SUFFIX"
	fi
	
	# Determine IE6 locale
	if [ "$CHOOSED_IE6_LOCALE" != "" ]; then
		if ! echo " $IE6_LOCALES " | grep " $CHOOSED_IE6_LOCALE " &> /dev/null; then
			error $MSG_ERROR_INVALIDLOCALE
		fi
		IE6_LOCALE=$CHOOSED_IE6_LOCALE
	else
		IE6_LOCALE=$GUESSED_IE6_LOCALE
	fi
}

# Show what we will do
{
	section $MSG_INSTALLATION_OPTIONS
		IES="6.0"
		[ "$INSTALLIE55" = "1" ] && IES="$IES, 5.5"
		[ "$INSTALLIE5"  = "1" ] && IES="$IES, 5.01"
		[ "$INSTALLIE1"  = "1" ] && IES="$IES, 1.0"
		[ "$INSTALLIE15"  = "1" ] && IES="$IES, 1.5"
		[ "$INSTALLIE2"  = "1" ] && IES="$IES, 2.0"
		[ "$INSTALLIE7"  = "1" ] && IES="$IES, 7.0"
		subsection - $MSG_OPTION_INSTALL_IES $IES
		subsection - $MSG_OPTION_LOCALE	 $IE6_LOCALE
	
		[ "$INSTALLFLASH" = "1" ] && subsection - $MSG_OPTION_INSTALL_FLASH
		[ "$CREATE_ICON" = "1"  ] && subsection - $MSG_OPTION_CREATE_ICONS
		subsection - $MSG_OPTION_BASEDIR $BASEDIR
		#subsection - $MSG_OPTION_DOWNLOADDIR $DOWNLOADDIR
	ok
}

# Prepare folders
{
	mkdir -p "$BINDIR"       || error $MSG_ERROR_CREATE_FOLDER $BINDIR
	mkdir -p "$BASEDIR/tmp/" || error $MSG_ERROR_CREATE_FOLDER $BASEDIR
	mkdir -p "$DOWNLOADDIR"  || error $MSG_ERROR_CREATE_FOLDER $DOWNLOADDIR
	cp "$IES4LINUX/lib/ies4linux.svg" "$BASEDIR"
}

source "$IES4LINUX/lib/install.sh"

section $MSG_INSTALLATIONS_FINISHED

# Show user how to run her IEs
{
	echo
	section $MSG_RUN_IES
	[ "$INSTALLIE6"  = "1" ] && run_ie 6
	[ "$INSTALLIE55" = "1" ] && run_ie 55
	[ "$INSTALLIE5"  = "1" ] && run_ie 5
	[ "$INSTALLIE1"  = "1" ] && run_ie 1
	[ "$INSTALLIE15"  = "1" ] && run_ie 15
	[ "$INSTALLIE2"  = "1" ] && run_ie 2
	[ "$INSTALLIE3"  = "1" ] && run_ie 3
	[ "$INSTALLIE7"  = "1" ] && run_ie 7
	echo
}
