#!/bin/bash
#
# IEs 4 Linux
# Developed by: Sergio Luis Lopes Junior <slopes at gmail dot com>
# Project site: http://tatanka.com.br/ies4linux
#
# Released under the GNU GPL. See LICENSE for more information

# Discover ies4linux installation folder (by Fernando Gomes)
IES4LINUX=`dirname $0`
cd $IES4LINUX
IES4LINUX=`pwd`
export IES4LINUX

# Do the installation
source lib/configure.sh
source lib/functions.sh
log "### IES4Linux Installation"

source lib/init.sh
source lib/download.sh

create_initial_folders
do_basic_installation

install_ie6
install_ie55
install_ie5

install_plugins
remove_extra_folders

print_section IEs4Linux installations finished!





