#!/usr/bin/env bash
#
# IEs 4 Linux GUI installer
# Developed by: Sergio Luis Lopes Junior <slopes at gmail dot com>
# Project site: http://tatanka.com.br/ies4linux
#
# Released under the GNU GPL. See LICENSE for more information

# Discover ies4linux installation folder
IES4LINUX=`dirname "$0"`
cd "$IES4LINUX"
export IES4LINUX=`pwd`

source lib/functions.sh
initDebug
initVariables
initLanguage

COMMAND_LINE_OPTIONS=$@

# possible UIs
function runUI(){
	debug Using $1 GUI
	python "$IES4LINUX"/ui/ies4linux.py $1 $COMMAND_LINE_OPTIONS
}

# Decide what UI to run
if python -c ""; then
	
	# detection based on easyubuntu detect.py#de()	

	hasgtk=$(python -c "import pygtk; pygtk.require('2.0'); import gtk" &> /dev/null; echo $?)
	hasqt=$(python -c "import qt" &> /dev/null; echo $?)

	if [ "$hasgtk" = "0" ]; then
		runUI gtk

#	For the near future
# 	if [ "$hasgtk" = "0" ] && [ "$hasqt" = "0" ]; then
# 		if  [ "$KDE_FULL_SESSION" = "true" ]; then
# 			runUI qt
# 		else
# 			runUI gtk
# 		fi
# 	elif [ "$hasgtk" = "0" ]; then
# 		runUI gtk
# 	elif [ "$hasqt" = "0" ]; then
# 		runUI qt

	else
		debug Could not find python
		warning $MSG_NO_GUI_AVAILABLE
	
		"$IES4LINUX"/ies4linux --help
	fi

else # no python
	debug Could not find python
	warning $MSG_ERROR_NO_GUI_AVAILABLE

	"$IES4LINUX"/ies4linux --help
fi
