#!/usr/bin/env bash
#
# IEs 4 Linux GUI installer
# Developed by: Sergio Luis Lopes Junior <slopes at gmail dot com>
# Project site: http://tatanka.com.br/ies4linux
#
# Released under the GNU GPL. See LICENSE for more information

# Discover ies4linux installation folder
IES4LINUX=`dirname "$0"`
cd "$IES4LINUX"
export IES4LINUX=`pwd`

source lib/functions.sh
initDebug
initVariables
initLanguage

COMMAND_LINE_OPTIONS=$@

# possible UIs
function runPyGTK(){
	debug Using pygtk GUI
	python "$IES4LINUX"/ui/ies4linux.py gtk $COMMAND_LINE_OPTIONS
}

function runKommander(){
	debug Using kommander gui
	source "$IES4LINUX"/ui/kommander.sh $COMMAND_LINE_OPTIONS
}

# Decide what UI to run
haspygtk=$(python -c "import pygtk; pygtk.require('2.0'); import gtk" &> /dev/null; echo $?)
haskmdr=$(kmdr-executor -v &> /dev/null; echo $?)

if [ "$haspygtk" = "0" ] && [ "$haskmdr" = "0" ]; then
	if  [ "$KDE_FULL_SESSION" = "true" ]; then
		runKommander
	else
		runPyGTK
	fi
elif [ "$haspygtk" = "0" ]; then
	runPyGTK
elif [ "$haskmdr" = "0" ]; then
	runKommander
else
	warning $MSG_NO_GUI_AVAILABLE
	"$IES4LINUX"/ies4linux --help
fi

